import os
import re
import glob
import json
from datetime import datetime
from pathlib import Path

# Paths
WORKSPACE = Path(__file__).resolve().parent.parent
AGENTS_DIR = WORKSPACE / ".agents"
MANIFEST_PATH = AGENTS_DIR / "MANIFEST.md"
GLOBAL_RULES_PATH = AGENTS_DIR / "rules" / "global.md"
PROJECT_PATH = AGENTS_DIR / "PROJECT.md"
COMMANDS_DIR = AGENTS_DIR / "commands"
PERSONAS_DIR = AGENTS_DIR / "personas"
RULES_DIVISIONS_DIR = AGENTS_DIR / "rules" / "divisions"

def get_iso_timestamp():
    return datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")

def read_file(path):
    if not path.exists():
        return ""
    with open(path, "r", encoding="utf-8") as f:
        return f.read()

def write_file(path, content):
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)

def parse_manifest():
    content = read_file(MANIFEST_PATH)
    
    # Extract routing table
    routing_match = re.search(r"## Skill Routing Table\s+.*?```\s*(.*?)\s*```", content, re.DOTALL)
    routing_table = routing_match.group(1) if routing_match else ""
    
    # Extract division registry
    division_match = re.search(r"## Division Registry\s+(.*?)\n---", content, re.DOTALL)
    division_registry = division_match.group(1).strip() if division_match else ""
    
    # Extract file locations
    file_loc_match = re.search(r"## File Locations — Where Each Agent Writes\s+(.*?)\n---", content, re.DOTALL)
    file_locations = file_loc_match.group(1).strip() if file_loc_match else ""

    return {
        "routing_table": routing_table,
        "division_registry": division_registry,
        "file_locations": file_locations
    }

def parse_global_rules():
    content = read_file(GLOBAL_RULES_PATH)
    # Extract rules
    rules = []
    matches = re.finditer(r"### (RULE \d+ — .*?)\n(.*?)(?=\n### |$)", content, re.DOTALL)
    for match in matches:
        title = match.group(1).strip()
        body = match.group(2).strip()
        # Get first sentence or two of body
        first_line = body.split("\n")[0]
        rules.append(f"- **{title}**: {first_line}")
    return "\n".join(rules)

def parse_project_config():
    content = read_file(PROJECT_PATH)
    
    # Extract stack
    stack_match = re.search(r"## Stack\s+(.*?)(?=\n##|$)", content, re.DOTALL)
    stack = stack_match.group(1).strip() if stack_match else ""
    
    # Extract conventions
    conv_match = re.search(r"## Conventions\s+(.*?)(?=\n##|$)", content, re.DOTALL)
    conventions = conv_match.group(1).strip() if conv_match else ""
    
    # Extract run commands
    run_match = re.search(r"## How to Run\s+```bash\s*(.*?)\s*```", content, re.DOTALL)
    run_commands = run_match.group(1).strip() if run_match else ""

    return {
        "stack": stack,
        "conventions": conventions,
        "run_commands": run_commands
    }

def get_commands_list():
    commands = []
    for filepath in sorted(COMMANDS_DIR.glob("*.md")):
        name = f"/{filepath.stem}"
        content = read_file(filepath)
        desc_match = re.search(r"#.*Skill\s+#\s*(.*?)(?=\n|$)", content)
        desc = desc_match.group(1).strip() if desc_match else "Agent system command"
        commands.append(f"- `{name}`: {desc}")
    return "\n".join(commands)

def get_division_rules(division_name):
    path = RULES_DIVISIONS_DIR / f"{division_name}.md"
    if not path.exists():
        return ""
    content = read_file(path)
    # Remove header
    content = re.sub(r"^#.*?\n", "", content)
    return content.strip()

def main():
    print("Starting sync-adapters...")
    ts = get_iso_timestamp()
    
    manifest = parse_manifest()
    global_rules = parse_global_rules()
    project = parse_project_config()
    commands = get_commands_list()
    
    engineering_rules = get_division_rules("engineering")
    design_rules = get_division_rules("design")

    # 1. Generate CLAUDE.md
    claude_content = f"""[DO NOT EDIT — auto-generated by /sync-adapters from .agents/ — Last synced: {ts}]
[To update this file, edit .agents/MANIFEST.md or .agents/PROJECT.md, then run /sync-adapters]

---

# Forge Nexus — Agent System

## How This System Works

This project uses a 6-division multi-agent system. The **Orchestrator** (Chief of Staff) plans, routes, and reviews all work. Each division has a **Lead** and **Specialists** who execute tasks within their domain. The Research Council handles high-stakes adversarial decisions.

Every skill runs an 8-step pre-flight: read MANIFEST → read rules → read PROJECT → read learned patterns → verify task → validate permissions → scope side-effects → log to audit. Nothing executes before the pre-flight passes.

## Agent Routing (use this table to pick the right command)

```
{manifest["routing_table"]}
```

## Ironclad Rules (always enforced)

{global_rules}

## Project Stack & Conventions

### Stack
{project["stack"]}

### Conventions
{project["conventions"]}

## Key Commands

{commands}

## Pre-Flight Sequence (every skill runs this before any action)

1. READ `.agents/MANIFEST.md`
2. READ `.agents/rules/global.md`
3. READ `.agents/PROJECT.md`
4. READ `.agents/learned.jsonl` (tag-filtered)
5. CHECK `.agents/task.md`
6. VALIDATE permission tiers
7. SCOPE all files to be touched
8. LOG activation to `audit.jsonl`

## File Locations

- Audit log: `.agents/audit.jsonl`
- Learned patterns: `.agents/learned.jsonl`
- Session task DAG: `.agents/task.md`
- Agent reports: `.agents/reports/`
- Council verdicts: `.agents/council/verdicts/`
- Session dashboards: `.agents/sessions/`
"""
    write_file(WORKSPACE / "CLAUDE.md", claude_content)
    print("Generated CLAUDE.md")

    # 2. Generate AGENTS.md
    agents_content = f"""[DO NOT EDIT — auto-generated by /sync-adapters from .agents/ — Last synced: {ts}]

# Forge Nexus — Agent Instructions

## Codebase Overview

This project uses a structured multi-agent system with 6 divisions. An Orchestrator coordinates all work. See `.agents/MANIFEST.md` for the full system specification.

### Project Stack
{project["stack"]}

## How to Run / Test

```bash
{project["run_commands"]}
```

## Commands & Routing

```
{manifest["routing_table"]}
```

## Rules

{global_rules}

## Project Conventions

{project["conventions"]}

## Key File Locations

- Master routing: `.agents/MANIFEST.md`
- Global rules: `.agents/rules/global.md`
- Project config: `.agents/PROJECT.md`
- Agent personas: `.agents/personas/`
- Command definitions: `.agents/commands/`
- Audit log: `.agents/audit.jsonl`
- Pattern memory: `.agents/learned.jsonl`
- Reports: `.agents/reports/`
"""
    write_file(WORKSPACE / "AGENTS.md", agents_content)
    print("Generated AGENTS.md")

    # 3. Generate .cursor/rules/agents.mdc
    cursor_agents = f"""---
description: "Forge Nexus agent system — core routing, ironclad rules, and conventions"
alwaysApply: true
---

# Agent Routing

```
{manifest["routing_table"]}
```

# Rules

{global_rules}

# Conventions

{project["conventions"]}

# Pre-Flight Sequence

1. READ `.agents/MANIFEST.md`
2. READ `.agents/rules/global.md`
3. READ `.agents/PROJECT.md`
4. READ `.agents/learned.jsonl` (tag-filtered)
5. CHECK `.agents/task.md`
6. VALIDATE permission tiers
7. SCOPE all files to be touched
8. LOG activation to `audit.jsonl`
"""
    write_file(WORKSPACE / ".cursor" / "rules" / "agents.mdc", cursor_agents)
    print("Generated .cursor/rules/agents.mdc")

    # 4. Generate .cursor/rules/frontend.mdc
    cursor_frontend = f"""---
description: "Frontend engineering and UI design rules"
globs: ["src/**/*.tsx", "src/**/*.ts", "src/**/*.css"]
alwaysApply: false
---

# Frontend Engineering Rules

{engineering_rules}

# Design Division Rules

{design_rules}
"""
    write_file(WORKSPACE / ".cursor" / "rules" / "frontend.mdc", cursor_frontend)
    print("Generated .cursor/rules/frontend.mdc")

    # 5. Generate .cursor/rules/backend.mdc
    cursor_backend = f"""---
description: "Backend engineering, API design, and DB rules"
globs: ["src/server/**", "src/api/**", "src/services/**", "src/routes/**", "prisma/**"]
alwaysApply: false
---

# Backend Engineering Rules

{engineering_rules}
"""
    write_file(WORKSPACE / ".cursor" / "rules" / "backend.mdc", cursor_backend)
    print("Generated .cursor/rules/backend.mdc")

    # 6. Update Manifest Last /sync-adapters field
    manifest_content = read_file(MANIFEST_PATH)
    updated_manifest = re.sub(
        r"Last /sync-adapters: \[.*?\]",
        f"Last /sync-adapters: {ts}",
        manifest_content
    )
    # Also update Updated: field near top
    updated_manifest = re.sub(
        r"Updated:\s+\[Orchestrator updates this on /sync-adapters\]",
        f"Updated:   {ts}",
        updated_manifest
    )
    write_file(MANIFEST_PATH, updated_manifest)
    print("Updated MANIFEST.md timestamp")
    
    print("Sync complete!")

if __name__ == "__main__":
    main()
